lunarlander13:
  env_id: LunarLander-v3
  replay_memory_size: 300000
  mini_batch_size: 64
  epsilon_init: 1.0
  epsilon_decay: 0.9995
  epsilon_min: 0.001
  network_sync_rate: 500
  learning_rate: 0.0001
  discount_factor_g: 0.99
  stop_on_reward: 500
  fc1_nodes: 256
  enable_double_dqn: False
  enable_dueling_dqn: False






  